[package]
name = "local"
version = "0.1.0"
edition = "2024"

[dependencies]
beat = { path = "../beat" }
event = { path = "../event" }
cue = { path = "../cue" }
mem = { path = "../mem" }
bitflags = { version = "2.10.0" }

[features]
