[package]
name = "mem"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { version = "2.0.1", features = ["derive"] }
bitflags = { version = "2.10.0", features = ["serde"] }
serde = { version = "1.0.228", optional = true, features = ["derive"] }

[features]
serde = ["dep:serde"]
