[package]
name = "cue"
version = "0.1.0"
edition = "2024"

[dependencies]
beat = { path = "../beat" }
bincode = { version = "2.0.1", features = ["derive"] }
event = { path = "../event" }
mem = { path = "../mem" }

[features]
std = []
